package org.aja.helloworld.resources;

import java.util.*;

public class TranslateService {

    List<Translate> words = new ArrayList<>();


    public TranslateService() {
        words.add(new Translate("hej", "salam"));
        words.add(new Translate("tack", "merci"));
        words.add(new Translate("jag", "man"));
        words.add(new Translate("du", "to"));
        words.add(new Translate("han", "oo"));
        words.add(new Translate("hon", "oo"));
        words.add(new Translate("vi", "maa"));
        words.add(new Translate("att gå", "raftan"));
        words.add(new Translate("att skriva", "neveshtan"));
        words.add(new Translate("jag gick", "man raftam"));
        words.add(new Translate("jag skrev", "man neveshtam"));
        words.add(new Translate("att se", "didan"));
        words.add(new Translate("jag såg", "man didam"));
        words.add(new Translate("att stänga", "bastan"));
        words.add(new Translate("jag stängde", "man bastam"));
        words.add(new Translate("att ta sönder", "shekastan"));
        words.add(new Translate("jag tog sönder", "man shekastam"));
        words.add(new Translate("att prata", "sohbat kardan "));
        words.add(new Translate("jag pratade", "man sohbat kardam"));
        words.add(new Translate("dörr", "dar"));
        words.add(new Translate("fönster", "panjereh"));
        words.add(new Translate("igår", "dirooz"));
        words.add(new Translate("idag", "emrooz"));
        words.add(new Translate("att pussa", "boosidan"));
        words.add(new Translate("jag pussade", "man boosidam"));
        words.add(new Translate("att ha", "dashtan"));
        words.add(new Translate("jag hade", "man dashtam"));
        words.add(new Translate("bord", "meez"));
        words.add(new Translate("glas", "livan"));
        words.add(new Translate("bok", "ketab"));
        words.add(new Translate("att städa", "tamiz kardan"));
        words.add(new Translate("att göra rent", "tamiz kardan"));
        words.add(new Translate("jag städade", "man tamiz kardam"));
        words.add(new Translate("att tvätta", "shostan"));
        words.add(new Translate("jag tvättade", "man shostam"));
        words.add(new Translate("att öppna", "baz kardan"));
        words.add(new Translate("jag öppnade", "man baz kardam"));
        words.add(new Translate("den här", "in"));
        words.add(new Translate("den där", "an"));
        words.add(new Translate("man", "mard"));
        words.add(new Translate("kvinna", "zan"));
        words.add(new Translate("att köpa", "kharidan"));
        words.add(new Translate("jag köpte", "man kharidam"));
        words.add(new Translate("vän", "doost"));
        words.add(new Translate("kompis", "doost"));
        words.add(new Translate("far", "pedar"));
        words.add(new Translate("mor", "madar"));
        words.add(new Translate("pappa", "baba"));
        words.add(new Translate("mamma", "maman"));
        words.add(new Translate("bror", "baradar"));
        words.add(new Translate("syster", "khahar"));
        words.add(new Translate("bil", "mashin"));
        words.add(new Translate("hus", "khaneh"));
        words.add(new Translate("hem", "khaneh"));
        words.add(new Translate("att sälja", "forookhtan"));
        words.add(new Translate("jag sålde", "man forookhtam"));
        words.add(new Translate("välkommen", "khosh amadid"));
        words.add(new Translate("hejdå", "khoda hafez"));
        words.add(new Translate("att läsa", "khandan"));
        words.add(new Translate("jag läste", "man khandam"));
        words.add(new Translate("att hitta", "peida kardan"));
        words.add(new Translate("jag hittade", "man peida kardam"));
        words.add(new Translate("att bygga", "sakhtan"));
        words.add(new Translate("jag byggde", "man sakhtam"));
        words.add(new Translate("förra året", "par sal"));
        words.add(new Translate("bro", "pol"));
        words.add(new Translate("att vara", "bodan"));
        words.add(new Translate("jag var", "man bodam"));
        words.add(new Translate("plötsligt", "nagahan"));
        words.add(new Translate("att knacka", "dar zadan"));
        words.add(new Translate("jag knackade", "man dar zadam"));
        words.add(new Translate("att stänga av", "khamush kardan"));
        words.add(new Translate("jag stängde av", "man khamush kardam"));
        words.add(new Translate("att ställa sig upp", "boland shodan"));
        words.add(new Translate("jag ställde mig upp", "man boland shodam"));
        words.add(new Translate("ensam", "tanha"));
        words.add(new Translate("korg", "sabad"));
        words.add(new Translate("en", "yek"));
        words.add(new Translate("att ta", "bardashtan, gereftan"));
        words.add(new Translate("jag tog", "man bardashtam, man gereftam"));
        words.add(new Translate("att tacka", "tashakor kardan"));
        words.add(new Translate("jag tackade", "man tashakor kardam"));
        words.add(new Translate("att sitta", "neshastan"));
        words.add(new Translate("jag satt", "man neshastam"));
        words.add(new Translate("marknad", "bazar"));
        words.add(new Translate("på", "dar"));
        words.add(new Translate("gata", "khiyaban"));
        words.add(new Translate("att komma", "amadan"));
        words.add(new Translate("jag kom", "man amadam"));
        words.add(new Translate("lärare", "moallem"));
        words.add(new Translate("vecka", "hafteh"));
        words.add(new Translate("frånvarande", "ghayeb"));
        words.add(new Translate("förra", "gozashteh"));
        words.add(new Translate("läxor", "mashgh"));
        words.add(new Translate("brev", "nameh"));
        words.add(new Translate("pojke", "pesar"));
        words.add(new Translate("kille", "pesar"));
        words.add(new Translate("flicka", "dokhtar"));
        words.add(new Translate("tjej", "dokhtar"));
        words.add(new Translate("natt", "shab"));
        words.add(new Translate("igår kväll", "dishab"));
        words.add(new Translate("ett", "yek"));
        words.add(new Translate("två", "do"));
        words.add(new Translate("tre", "seh"));
        words.add(new Translate("fyra", "chahar"));
        words.add(new Translate("fem", "panj"));
        words.add(new Translate("sex", "shish"));
        words.add(new Translate("sju", "haft"));
        words.add(new Translate("åtta", "hasht"));
        words.add(new Translate("nio", "noh"));
        words.add(new Translate("tio", "dah"));
        words.add(new Translate("elva", "yazdah"));
        words.add(new Translate("tolv", "davazdah"));
        words.add(new Translate("tretton", "sizdah"));
        words.add(new Translate("fjorton", "chahardah"));
        words.add(new Translate("femton", "panzdah"));
        words.add(new Translate("sexton", "shanzdah"));
        words.add(new Translate("sjutton", "hevdah"));
        words.add(new Translate("arton", "hezhdah"));
        words.add(new Translate("nitton", "nuzdah"));
        words.add(new Translate("tjugo", "bist"));
        words.add(new Translate("skola", "madreseh"));
        words.add(new Translate("huvud", "sar"));
        words.add(new Translate("att putta", "hol dadan"));
        words.add(new Translate("jag puttade", "man hol dadam"));
        words.add(new Translate("att döda", "koshtan"));
        words.add(new Translate("jag dödade", "man koshtam"));
        words.add(new Translate("hund", "sag"));
        words.add(new Translate("sedan", "pish"));
        words.add(new Translate("eftermiddag", "bad az zohr"));
        words.add(new Translate("att stjäla", "dozdidan"));
        words.add(new Translate("jag stal", "man dozdidam"));
        words.add(new Translate("ung", "javan"));
        words.add(new Translate("dam", "khanom"));
        words.add(new Translate("fru", "khanom"));
        words.add(new Translate("att röra", "dast zadan"));
        words.add(new Translate("jag rörde", "man dast zadam"));
        words.add(new Translate("studerande", "danesh amuz"));
        words.add(new Translate("morgon", "sobh"));
        words.add(new Translate("att slå", "zadan"));
        words.add(new Translate("jag slog", "man zadam"));
        words.add(new Translate("tv", "televizion"));
        words.add(new Translate("mataffär", "super market"));
        words.add(new Translate("kött", "gosht"));
        words.add(new Translate("glass", "bastani"));
        words.add(new Translate("mjölk", "shir"));
        words.add(new Translate("att gilla", "doost dashtan"));
        words.add(new Translate("jag gillade", "man doost dashtam"));
        words.add(new Translate("jag gillar", "man doost daram"));
        words.add(new Translate("boll", "toop"));
        words.add(new Translate("att titta på", "negah kardan"));
        words.add(new Translate("jag tittade", "man negah kardam "));
        words.add(new Translate("ballong", "bad konak"));
        words.add(new Translate("barn", "bacheh"));
        words.add(new Translate("cyckel", "do charkheh"));
        words.add(new Translate("hand", "dast"));
        words.add(new Translate("nål", "suzan"));
        words.add(new Translate("tjock", "chagh"));
        words.add(new Translate("att skrika", "jigh zadan"));
        words.add(new Translate("jag skrek", "man jigh zadam"));
        words.add(new Translate("att skratta", "khandidan"));
        words.add(new Translate("jag skrattade", "man khandidam"));
        words.add(new Translate("att hoppa", "paridan"));
        words.add(new Translate("jag hoppade", "man paridam"));
        words.add(new Translate("längre", "digar"));
        words.add(new Translate("trettio", "si"));
        words.add(new Translate("fyrtio", "che hel"));
        words.add(new Translate("femtio", "panjah"));
        words.add(new Translate("sextio", "shast"));
        words.add(new Translate("sjuttio", "haftad"));
        words.add(new Translate("åttio", "hashtad"));
        words.add(new Translate("nittio", "navad"));
        words.add(new Translate("hundra", "sad"));
        words.add(new Translate("tjugoett", "bist-o-yek"));
        words.add(new Translate("tjugotvå", "bist-o-do"));
        words.add(new Translate("tjugotre", "bist-o-seh"));
        words.add(new Translate("tjugofyra", "bist-o-chahar"));
        words.add(new Translate("tjugofem", "bist-o-panj"));
        words.add(new Translate("tjugosex", "bist-o-shish"));
        words.add(new Translate("tjugosju", "bist-o-haft"));
        words.add(new Translate("tjugoåtta", "bist-o-hasht"));
        words.add(new Translate("tjugonio", "bist-o-noh"));
        words.add(new Translate("land", "keshvar"));
        words.add(new Translate("choklad", "shokolat"));
        words.add(new Translate("att äta", "khordan"));
        words.add(new Translate("jag åt", "man khordam"));
        words.add(new Translate("yngre", "kuchek"));
        words.add(new Translate("liten", "kuchek"));
        words.add(new Translate("att fånga", "gereftan"));
        words.add(new Translate("jag fångade", "man gereftam"));
        words.add(new Translate("mus", "mosh"));
        words.add(new Translate("vit", "sefid"));
        words.add(new Translate("häst", "asb"));
        words.add(new Translate("svart", "siyah, meskhi"));
        words.add(new Translate("drake", "badbadak"));
        words.add(new Translate("tallrik", "boshghab"));
        words.add(new Translate("att flyga", "parvaz kardan"));
        words.add(new Translate("jag flög", "man parvaz kardam"));
        words.add(new Translate("katt", "gorbeh"));
        words.add(new Translate("herr", "agha"));
        words.add(new Translate("karl", "agha"));
        words.add(new Translate("rum", "otagh"));
        words.add(new Translate("vem", "ki"));
        words.add(new Translate("vad", "chi"));
        words.add(new Translate("stor", "bozorg"));
        words.add(new Translate("granne", "hamsayeh"));
        words.add(new Translate("bra", "khub"));
        words.add(new Translate("lång", "boland"));
        words.add(new Translate("kort", "kutah"));
        words.add(new Translate("längd", "ghad"));
        words.add(new Translate("ny", "tazeh, jadid"));
        words.add(new Translate("förrigår", "pariruz"));
        words.add(new Translate("att sätta på", "roshan kardan"));
        words.add(new Translate("jag satte på", "man roshan kardam"));
        words.add(new Translate("dator", "kamputer"));
        words.add(new Translate("att stänga av", "khamush kardan"));
        words.add(new Translate("jag stängde av", "man khamush kardam"));
        words.add(new Translate("make", "shohar"));
        words.add(new Translate("lampa", "lamp"));
        words.add(new Translate("klocka", "sa at"));
        words.add(new Translate("maka", "zan"));
        words.add(new Translate("flera", "chandin"));
        words.add(new Translate("fin", "ghashang"));
        words.add(new Translate("ful", "zesht"));
        words.add(new Translate("dålig", "bad"));
        words.add(new Translate("blomma", "gol"));
        words.add(new Translate("att ta emot", "daryaft kardan"));
        words.add(new Translate("jag tog emot", "man daryaft kardam"));
        words.add(new Translate("sår", "zakhm"));
        words.add(new Translate("att förstöra", "kharab kardan"));
        words.add(new Translate("jag förstörde", "man kharab kardam"));
        words.add(new Translate("att tappa bort", "gom kardan"));
        words.add(new Translate("jag tappade bort", "man gom kardam"));
        words.add(new Translate("klasskompis", "ham kelasi"));
        words.add(new Translate("schaktningsmaskin", "boldozer"));
        words.add(new Translate("bulldozer", "boldozer"));
        words.add(new Translate("penna", "medad"));
        words.add(new Translate("att ge", "dadan"));
        words.add(new Translate("jag gav", "man dadam"));
        words.add(new Translate("buss", "oto bos"));
        words.add(new Translate("väska", "kif"));
        words.add(new Translate("att skära", "boridan"));
        words.add(new Translate("jag skar", "man boridam"));
        words.add(new Translate("träd", "derakht"));
        words.add(new Translate("att plantera", "kashtan"));
        words.add(new Translate("jag planterade", "man kashtam"));
        words.add(new Translate("kniv", "chaghu, kard"));
        words.add(new Translate("kök", "ashpaz khaneh"));
        words.add(new Translate("gardin", "pardeh"));
        words.add(new Translate("att laga", "tamir kardan"));
        words.add(new Translate("jag lagade", "man tamir kardam"));
        words.add(new Translate("låda", "jabeh"));
        words.add(new Translate("fågel", "parandeh"));
        words.add(new Translate("röd", "ghermez"));
        words.add(new Translate("gul", "zard"));
        words.add(new Translate("blå", "abi"));
        words.add(new Translate("grön", "sabz"));
        words.add(new Translate("lila", "banafsh"));
        words.add(new Translate("tvåhundra", "devist"));
        words.add(new Translate("trehundra", "sisad"));
        words.add(new Translate("fyrahundra", "chaharsad"));
        words.add(new Translate("femhundra", "pansad"));
        words.add(new Translate("skärp", "kamar band"));
        words.add(new Translate("rygg", "kamar"));
        words.add(new Translate("affär", "maghazeh"));
        words.add(new Translate("butiksinnehavare", "maghazeh dar"));
        words.add(new Translate("butik", "maghazeh"));
        words.add(new Translate("byxor", "shalvar"));
        words.add(new Translate("att publicera", "enteshar dadan"));
        words.add(new Translate("jag publicerade", "man enteshar dadam"));
        words.add(new Translate("port", "darvazeh"));
        words.add(new Translate("jacka", "kot, kapchen"));
        words.add(new Translate("brun", "ghahveh i"));
        words.add(new Translate("grå", "khakestari"));
        words.add(new Translate("orange", "narenji"));
        words.add(new Translate("himmel", "aseman"));
        words.add(new Translate("himmelsblå", "abi ye asemani"));
        words.add(new Translate("ljus", "roshan"));
        words.add(new Translate("mörk", "tireh (färger), tarik"));
        words.add(new Translate("sexhundra", "shesh sad"));
        words.add(new Translate("sjuhundra", "haft sad"));
        words.add(new Translate("åttahundra", "hasht sad"));
        words.add(new Translate("niohundra", "noh sad"));
        words.add(new Translate("tusen", "hezar"));
        words.add(new Translate("tiotusen", "dah hezar"));
        words.add(new Translate("hundratusen", "sad hezar"));
        words.add(new Translate("en miljon", "yek milyun"));
        words.add(new Translate("noll", "sefr"));
        words.add(new Translate("att stoppa", "motevaghef kardan"));
        words.add(new Translate("jag stoppade", "man motevaghef kardam"));
        words.add(new Translate("polis", "polis"));
        words.add(new Translate("mekaniker", "mekanik"));
        words.add(new Translate("motorcyckel", "motor siklet"));
        words.add(new Translate("att måla", "rang kardan"));
        words.add(new Translate("jag målade", "man rang kardam"));
        words.add(new Translate("vägg", "divar"));
        words.add(new Translate("gammal", "kohneh, pir ålder)"));
        words.add(new Translate("kock", "ash paz"));
        words.add(new Translate("att laga mat", "pokhtan"));
        words.add(new Translate("jag lagade mat", "man (gazah) pokhtam"));
        words.add(new Translate("tårta", "keik"));
        words.add(new Translate("knivarna", "chaghu ha"));
        words.add(new Translate("att lyda", "eta at kardan"));
        words.add(new Translate("lag", "ghanun"));
        words.add(new Translate("fisk", "mahi"));
        words.add(new Translate("jordbävning", "zel zeleh"));
        words.add(new Translate("bomb", "bomb"));
        words.add(new Translate("folk", "mardom"));
        words.add(new Translate("att skicka", "ferestadan"));
        words.add(new Translate("jag skickade", "man ferestadam"));
        words.add(new Translate("att äta", "khordan"));
        words.add(new Translate("jag åt", "man khordam"));
        words.add(new Translate("vattenmelon", "hendavaneh"));
        words.add(new Translate("matta", "farsh"));
        words.add(new Translate("att parkera", "park kardan"));
        words.add(new Translate("jag parkerade", "man park kardam"));
        words.add(new Translate("utomhus", "birun"));
        words.add(new Translate("kontor", "daftar"));
        words.add(new Translate("att utfärda", "sader kardan"));
        words.add(new Translate("jag utfärdade", "man sader kardam"));
        words.add(new Translate("biljett", "belit"));
        words.add(new Translate("att bötfälla", "jarimeh kardan"));
        words.add(new Translate("att betala", "pardakht kardan"));
        words.add(new Translate("jag betalade", "man pardakht kardam"));
        words.add(new Translate("piano", "piyano"));
        words.add(new Translate("skuld", "bedeh kari"));
        words.add(new Translate("att introducera", "moarefi kardan"));
        words.add(new Translate("jag introducerade", "man moarefi kardam"));
        words.add(new Translate("metod", "ravesh"));
        words.add(new Translate("lunch", "nahar"));
        words.add(new Translate("middag", "sham"));
        words.add(new Translate("frukost", "sob haneh"));
        words.add(new Translate("pris", "jayezeh"));
        words.add(new Translate("chaufför", "ranandeh"));
        words.add(new Translate("att säga", "goftan"));
        words.add(new Translate("jag sa", "man goftam"));
        words.add(new Translate("president", "raees e jomhur"));
        words.add(new Translate("att avgå", "estefa dadan"));
        words.add(new Translate("jag avgick", "man estefa dadam"));
        words.add(new Translate("premiärminister", "nakhost vazir"));
        words.add(new Translate("hopp", "omid"));
        words.add(new Translate("att lämna", "tark kardan"));
        words.add(new Translate("taxi", "taksi"));
        words.add(new Translate("taxi chaufför", "ranandeh ye taksi"));
        words.add(new Translate("något", "chizi"));
        words.add(new Translate("salt", "namak"));
        words.add(new Translate("peppar", "felfel"));
        words.add(new Translate("ris", "berenj, polo(med innehåll)"));
        words.add(new Translate("kyckling", "morgh, djodje"));
        words.add(new Translate("kläder", "lebas"));
        words.add(new Translate("månad", "mah"));
        words.add(new Translate("måne", "mah"));
        words.add(new Translate("mat", "ghaza"));
        words.add(new Translate("flera", "chandin"));
        words.add(new Translate("att ringa", "telefon kardan"));
        words.add(new Translate("jag ringde", "man telefon kardam"));
        words.add(new Translate("att leka", "bazi kardan"));
        words.add(new Translate("jag lekte", "man bazi kardam"));
        words.add(new Translate("radio", "radio"));
        words.add(new Translate("elektricitet", "bargh"));
        words.add(new Translate("el", "bargh"));
        words.add(new Translate("att hyra", "ejareh kardan"));
        words.add(new Translate("jag hyrde", "man ejareh kardam"));
        words.add(new Translate("rum", "otagh"));
        words.add(new Translate("att byta", "avaz kardan"));
        words.add(new Translate("jag bytte", "man avaz kardam"));
        words.add(new Translate("föräldrar", "valedein, pedar-o-madar (vardagligt)"));
        words.add(new Translate("jobb", "kar, shoghl"));
        words.add(new Translate("medicin", "daru"));
        words.add(new Translate("plånbok", "kif e pul"));
        words.add(new Translate("någon", "kesi"));
        words.add(new Translate("ingen", "hich kas"));
        words.add(new Translate("måndag", "do shan beh"));
        words.add(new Translate("tisdag", "seh shan beh"));
        words.add(new Translate("onsdag", "chahar shan beh"));
        words.add(new Translate("torsdag", "panj shan beh"));
        words.add(new Translate("fredag", "jomeh"));
        words.add(new Translate("lördag", "shan beh"));
        words.add(new Translate("söndag", "yek shan beh"));
        words.add(new Translate("present", "hedyeh"));
        words.add(new Translate("dikter", "sher"));
        words.add(new Translate("födelsedagskalas", "jashn e tavalod"));
        words.add(new Translate("födelsedag", "tavalod"));
        words.add(new Translate("grattis på födelsedagen", "tavalodet mobarak"));
        words.add(new Translate("flickvän", "dust dokhtar"));
        words.add(new Translate("pojkvän", "dust pesar"));
        words.add(new Translate("fotboll", "futbal"));
        words.add(new Translate("match", "mosabegheh"));
        words.add(new Translate("författare", "nevisandeh"));
        words.add(new Translate("att uppleva", "tajrobeh kardan"));
        words.add(new Translate("olycka", "tasadof"));
        words.add(new Translate("att acceptera", "ghabul kardan"));
        words.add(new Translate("jag accepterade", "man ghabul kardam"));
        words.add(new Translate("förslag", "pish nahad"));
        words.add(new Translate("jag ska", "khaham"));
        words.add(new Translate("du ska", "khahi"));
        words.add(new Translate("att dricka", "nushidan"));
        words.add(new Translate("jag drack", "man nushidam"));
        words.add(new Translate("läsk", "nushidan"));
        words.add(new Translate("sol", "khorshid, aftab"));
        words.add(new Translate("att skina", "derakh shidan"));
        words.add(new Translate("jag sken", "man derakh shidam"));
        words.add(new Translate("att föredra", "tarjih dadan"));
        words.add(new Translate("jag föredrog", "man tarjih dadam"));
        words.add(new Translate("att välja", "entekhab kardan"));
        words.add(new Translate("jag valde", "man entekhab kardam"));
        words.add(new Translate("att fira", "jashn gereftan"));
        words.add(new Translate("jag firade", "man jashn gereftam"));
        words.add(new Translate("nyår", "sal-e-no"));
        words.add(new Translate("att respektera", "ehteram gozashtan"));
        words.add(new Translate("att be", "doa kardan"));
        words.add(new Translate("jag respekterade", "man ehteram gozashtam"));
        words.add(new Translate("jag bad", "man doa kardam"));
        words.add(new Translate("att gråta", "geryeh kardan"));
        words.add(new Translate("jag grät", "man geryeh kardam"));
        words.add(new Translate("att gifta sig", "ezdevaj kardan "));
        words.add(new Translate("jag gifte mig", "man ezdevaj kardam"));
        words.add(new Translate("att bli", "shodan"));
        words.add(new Translate("jag blev", "man shodam"));
        words.add(new Translate("ledsen", "gham gin"));
        words.add(new Translate("glad", "khosh hal"));
        words.add(new Translate("domare", "davar"));
        words.add(new Translate("att räkna", "shemordan"));
        words.add(new Translate("jag räknade", "man shemordam"));
        words.add(new Translate("att migrera", "mohajerat kardan"));
        words.add(new Translate("jag migrerade", "man mohajerat kardam"));
        words.add(new Translate("till", "beh"));
        words.add(new Translate("söder", "jonub"));
        words.add(new Translate("höst", "paeez"));
        words.add(new Translate("att fängsla", "zendani kardan"));
        words.add(new Translate("staten", "dolat"));
        words.add(new Translate("att följa efter", "donbal kardan"));
        words.add(new Translate("jag följde efter", "man donbal kardam"));
        words.add(new Translate("lektion", "dars"));
        words.add(new Translate("att glömma", "faramush kardan"));
        words.add(new Translate("jag glömde", "man faramush kardam"));
        words.add(new Translate("pass", "pasport"));
        words.add(new Translate("flygplats", "forudgah"));
        words.add(new Translate("att skicka", "ferestadan"));
        words.add(new Translate("jag skickade", "man ferestadam"));
        words.add(new Translate("från", "az"));
        words.add(new Translate("ingen", "hich"));
        words.add(new Translate("imorgon", "farda"));
        words.add(new Translate("nästa", "ayandeh (tid)"));
        words.add(new Translate("att lära", "yad gereftan"));
        words.add(new Translate("jag lärde mig", "man yad gereftam"));
        words.add(new Translate("språk", "zaban"));                  //gh ge
        words.add(new Translate("att förlåta", "bakh shidan"));   //kh = khe
        words.add(new Translate("jag förlät", "man bakh shidam"));  //ch = she
    words.add(new Translate("chef", "modir"));                          //sh = she
        words.add(new Translate("projekt", "porujeh"));
        words.add(new Translate("att avbryta", "laghv kardan"));
        words.add(new Translate("jag avbröt", "man laghv kardam"));
        words.add(new Translate("att samarbeta", "ham kari kardan"));
        words.add(new Translate("jag samarbetade", "man ham kari kardam"));
        words.add(new Translate("att förändra", "taghir dadan"));
        words.add(new Translate("jag förändrade", "man taghir dadam"));
        words.add(new Translate("plan", "barnameh"));
        words.add(new Translate("sommar", "tabestan"));
        words.add(new Translate("kommande", "ayandeh (tid)"));
        words.add(new Translate("godmorgon", "sobh beh kheir"));
        words.add(new Translate("godnatt", "shab beh kheir"));
        words.add(new Translate("att återvända", "bar gashtan"));
        words.add(new Translate("jag återvände", "man bar gashtam"));
        words.add(new Translate("att rädda", "nejat dadan"));
        words.add(new Translate("jag räddade", "man nejat dadam"));
        words.add(new Translate("att vänja sig", "adat kardan"));
        words.add(new Translate("jag vande mig", "man adat kardam"));
        words.add(new Translate("att fråga", "porsidan"));
        words.add(new Translate("jag frågade", "man porsidam"));
        words.add(new Translate("namn", "esm, nam"));
        words.add(new Translate("flygplan", "hava peima"));
        words.add(new Translate("skjorta", "pirahan"));
        words.add(new Translate("hämnd", "entegham"));
        words.add(new Translate("att hämnas", "entegham gereftan"));
        words.add(new Translate("att leta", "donbal gashtan"));
        words.add(new Translate("vatten", "ab"));
        words.add(new Translate("att börja", "shoru kardan"));
        words.add(new Translate("jag började", "man shoru kardam"));
        words.add(new Translate("att avsluta", "tamam kardan"));
        words.add(new Translate("jag avslutade", "man tamam kardam"));
        words.add(new Translate("väldigt", "kheili"));
        words.add(new Translate("sent", "dir"));
        words.add(new Translate("gäst", "mehman"));
        words.add(new Translate("tidigt", "zud"));
        words.add(new Translate("mycket av", "ziyadi"));
        words.add(new Translate("att samlas", "jam shodan"));
        words.add(new Translate("bakom", "posht"));
        words.add(new Translate("några", "tedadi"));
        words.add(new Translate("en del", "meghdari"));
        words.add(new Translate("party", "jashn"));
        words.add(new Translate("fest", "mehmooni"));
        words.add(new Translate("socker", "shekar"));
        words.add(new Translate("och", "va"));
        words.add(new Translate("att spendera", "kharj kardan"));
        words.add(new Translate("jag spenderade", "man kharj kardam"));
        words.add(new Translate("pengar", "pul"));
        words.add(new Translate("att lova", "ghol dadan"));
        words.add(new Translate("jag lovade", "man ghol dadam"));
        words.add(new Translate("att bestämma", "tasmim gereftan"));
        words.add(new Translate("att sluta", "mote vaghef kardan"));
        words.add(new Translate("ambassad", "sefarat"));
        words.add(new Translate("visum", "viza"));
        words.add(new Translate("gräns", "marz"));
        words.add(new Translate("plats", "ja"));
        words.add(new Translate("att anlända", "residan"));
        words.add(new Translate("jag anlände", "man residam"));
        words.add(new Translate("problem", "moshkel"));
        words.add(new Translate("att lösa", "hal kardan"));
        words.add(new Translate("jag löste", "man hal kardam"));
        words.add(new Translate("tyskland", "alman"));
        words.add(new Translate("england", "engelestan, engelis"));
        words.add(new Translate("amerika", "amrika"));
        words.add(new Translate("usa", "amrika"));
        words.add(new Translate("kanada", "kanada"));
        words.add(new Translate("schweiz", "suiss"));
        words.add(new Translate("brasilien", "berezil"));
        words.add(new Translate("holland", "holand"));
        words.add(new Translate("nederländerna", "holand"));
        words.add(new Translate("australien", "ostraliya"));
        words.add(new Translate("norge", "norvezh"));
        words.add(new Translate("spanien", "espaniya"));
        words.add(new Translate("sverige", "sued"));
        words.add(new Translate("saudiarabien", "arabestan-e-saudi"));
        words.add(new Translate("ungern", "majarestan"));
        words.add(new Translate("ryssland", "shoravi, rusiyeh"));
        words.add(new Translate("danmark", "dan mark"));
        words.add(new Translate("belgien", "bel zhik"));
        words.add(new Translate("japan", "zhapon"));
        words.add(new Translate("turkiet", "torki yeh"));
        words.add(new Translate("mexiko", "mek zik"));
        words.add(new Translate("kina", "chin"));
        words.add(new Translate("polen", "lahestan"));
        words.add(new Translate("kaffe", "ghahveh"));
        words.add(new Translate("te", "chai"));
        words.add(new Translate("golv", "zamin"));
        words.add(new Translate("tak", "sakhf"));
        words.add(new Translate("mormor", "madar bozorg"));
        words.add(new Translate("farmor", "madar bozorg"));
        words.add(new Translate("morfar", "pedar bozorg"));
        words.add(new Translate("farfar", "pedar bozorg"));
        words.add(new Translate("ålder", "sen"));
        words.add(new Translate("att resa", "safar kardan"));
        words.add(new Translate("jag reste", "man safar kardam"));
        words.add(new Translate("stol", "sandali"));
        words.add(new Translate("vår", "bahar"));
        words.add(new Translate("vinter", "zemestan"));
        words.add(new Translate("trött", "khaste"));
        words.add(new Translate("ost", "panir"));
        words.add(new Translate("gå härifrån", "boro"));
        words.add(new Translate("jag går härifrån", "man miram"));
        words.add(new Translate("ät", "bokhor"));
        words.add(new Translate("jag äter", "man mikhoram"));
        words.add(new Translate("skriv", "benevis"));
        words.add(new Translate("jag skriver", "man minevisam"));
        words.add(new Translate("jag sitter", "man mineshinam"));
        words.add(new Translate("jag skickar", "man miferestam"));
        words.add(new Translate("jag dödar", "man mikosham"));
        words.add(new Translate("jag slår", "man mizanam"));
        words.add(new Translate("jag blir", "man misham"));
        words.add(new Translate("jag tar sönder", "man mishkanam"));
        words.add(new Translate("jag hämtar", "man mi avaram"));
        words.add(new Translate("jag köper", "man mikharam"));
        words.add(new Translate("sitt", "beshin"));
        words.add(new Translate("skicka", "beferest"));
        words.add(new Translate("döda", "bokosh"));
        words.add(new Translate("slå", "bezan"));
        words.add(new Translate("ta sönder", "beshekan"));
        words.add(new Translate("bli", "besho"));
        words.add(new Translate("hämta", "bi yar"));
        words.add(new Translate("köp", "bekhar"));
        words.add(new Translate("fånga", "begir"));
        words.add(new Translate("välj", "entekhab kon"));
        words.add(new Translate("han", "oo"));
        words.add(new Translate("jag väljer", "man entekhab mikonam"));
        words.add(new Translate("kom", "biya"));
        words.add(new Translate("jag kommer", "man miyam"));
        words.add(new Translate("skär", "bebor"));
        words.add(new Translate("jag skär", "man mi boram"));
        words.add(new Translate("varje", "har"));
        words.add(new Translate("luft", "hava"));
        words.add(new Translate("hjärta", "ghalb, del"));
        words.add(new Translate("huvud", "sar"));
        words.add(new Translate("fot", "pah"));
        words.add(new Translate("rumpa", "kon"));
        words.add(new Translate("rygg", "kamar"));
        words.add(new Translate("bara", "faghat"));
        words.add(new Translate("tystnad", "sokut"));
        words.add(new Translate("färg", "rang"));
        words.add(new Translate("släkt", "khane vadeh"));
        words.add(new Translate("i vanliga fall", "mamulan"));
        words.add(new Translate("vanligen", "mamulan"));
        words.add(new Translate("park", "park"));
        words.add(new Translate("ja", "baleh, are"));
        words.add(new Translate("nej", "nah"));
        words.add(new Translate("kanske", "shayad"));
        words.add(new Translate("ingen orsak", "khahesh mi konam"));
        words.add(new Translate("varsågod", "befarmaid, khahesh mi konam"));
        words.add(new Translate("ursäkta", "bebakhshid"));
        words.add(new Translate("förlåt", "bebakhshid, mazerat mikham, motasef am"));
        words.add(new Translate("bra jobbat", "damet garm"));
        words.add(new Translate("bravo", "eyval"));
        words.add(new Translate("jag är på", "paye am"));
        words.add(new Translate("idiot", "oskol"));
        words.add(new Translate("väder", "hava"));
        words.add(new Translate("regn", "barun"));
        words.add(new Translate("snö", "barf"));
        words.add(new Translate("tuggummi", "adams"));
        words.add(new Translate("kram", "baghal"));
        words.add(new Translate("vänta", "sabr kon"));
        words.add(new Translate("okej", "bashe, okey"));
        words.add(new Translate("mer", "bishtar"));
        words.add(new Translate("sömn", "khab"));
        words.add(new Translate("igen", "dobareh"));
        words.add(new Translate("galen", "divone"));
        words.add(new Translate("hände", "shod"));
        words.add(new Translate("godkväll", "asr beh kheir"));
        words.add(new Translate("gott nytt år", "sal-e no mobarak"));
        words.add(new Translate("god jul", "kerismas mobarak"));
        words.add(new Translate("grattis", "tabrik migam"));
        words.add(new Translate("dag", "rooz"));
        words.add(new Translate("kväll", "asr"));
        words.add(new Translate("jag vet inte", "man nemidonam"));
        words.add(new Translate("titta", "negah kon"));
        words.add(new Translate("verkligen", "vaghean"));
        words.add(new Translate("skynda", "ajaleh kon"));
        words.add(new Translate("nu", "alan"));
        words.add(new Translate("prosit", "afiat bashe"));
        words.add(new Translate("vad är klockan", "sa'at chande"));
        words.add(new Translate("ko", "gav"));
        words.add(new Translate("senare", "badan"));
        words.add(new Translate("kropp", "badan, tan"));
        words.add(new Translate("trappa", "pelle"));
        words.add(new Translate("skalle", "kalle"));
        words.add(new Translate("människa", "adam"));
        words.add(new Translate("strykjärn", "oto"));
        words.add(new Translate("låda", "jabeh"));
        words.add(new Translate("flaska", "botri"));
        words.add(new Translate("cyckel", "do charkhe"));
        words.add(new Translate("stad", "shahr"));
        words.add(new Translate("huvudstad", "paye takht"));
        words.add(new Translate("tavla", "tablo"));
        words.add(new Translate("sallad", "salad"));
        words.add(new Translate("te", "chai"));
        words.add(new Translate("kaffe", "ghahve"));
        words.add(new Translate("soldat", "sarbaz"));
        words.add(new Translate("svärd", "sham shir"));
        words.add(new Translate("mjölk", "shir"));
        words.add(new Translate("lejon", "shir"));
        words.add(new Translate("vattenkran", "shir"));
        words.add(new Translate("gurka", "khiyar"));
        words.add(new Translate("tomat", "goje farangi"));
        words.add(new Translate("morot", "havij"));
        words.add(new Translate("tröja", "boloz"));
        words.add(new Translate("skor", "kafsh"));
        words.add(new Translate("strumpor", "jorab"));
        words.add(new Translate("finger", "angosht"));
        words.add(new Translate("banan", "mooz"));
        words.add(new Translate("äpple", "sib"));
        words.add(new Translate("päron", "golabi"));
        words.add(new Translate("vindruvor", "angor"));
        words.add(new Translate("hår", "mo"));
        words.add(new Translate("nagel", "nakhon"));
        words.add(new Translate("naglar", "nakhon"));
        words.add(new Translate("fingrar", "angosht"));
        words.add(new Translate("badkar", "van"));
        words.add(new Translate("badrum", "hamam"));
        words.add(new Translate("ögon", "cheshm"));
        words.add(new Translate("öron", "goosh"));
        words.add(new Translate("sköldpadda", "lak posht"));
        words.add(new Translate("gris", "khook"));

    }

    public Translate getPersianWord(String swedish){
        Optional<Translate> first = words.stream().filter(z -> z.getSwedish().equals(swedish)).findFirst();
        return first.orElse(new Translate(swedish, "not found"));
    }

    Translate getSwedishWord(String persian){
        Optional<Translate> first = words.stream().filter(z -> z.getPersian().equals(persian)).findFirst();
        return first.orElse(new Translate("not found", persian));
    }

    public int getCount() {
        return words.size();
    }

    public List<Translate> getAllWords() {

        return words;
    }
}
